services:
  frontend:
    build: 
      context: ./frontend 
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/var/www/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true 
    networks:
      - app-network
    depends_on:
        - backend
    command: >
      sh -c "
        until curl -s http://backend:8000/api/test; do
          echo 'Waiting for Laravel to start...';
          sleep 5;
        done;
        npm start
      "
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/backend
    env_file:
    - ./backend/.env
    networks:
      - app-network
    depends_on:
      - mysql
    command: >
      sh -c "
      until nc -z -v -w30 mysql 3306; do
        echo 'Waiting for database connection...';
        sleep 5;
      done;
      php artisan migrate --force &&
      php artisan serve --host=0.0.0.0 --port=8000
      "

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: user_db
      MYSQL_ROOT_PASSWORD: 123 # 改成登入密碼
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
      